=== natahiko/XML-Trainings/testShema/husband.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="husband">
        <xs:sequence>
            <!--            NAME-->
            <xs:element name="name" type="xs:string"/>

            <!--            EMAIL-->
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[^@]+@[^\.]+\..+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:group ref="eye_hair"/>
            <!--            HEIGHT-->
            <xs:element name="height">
                <xs:simpleType>
                    <xs:restriction base="xs:double">
                        <xs:minInclusive value="55.0"/>
                        <xs:maxInclusive value="280.0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

<!--    EYE AND HAIR COLORS IN ANY ORDER-->
    <xs:group name="eye_hair">
        <xs:choice>
            <xs:sequence>
                <xs:element name="eyes_color" type="eyes_color"/>
                <xs:element name="hair_color" type="hair_color"/>
            </xs:sequence>
            <xs:sequence>
                <xs:element name="hair_color" type="hair_color"/>
                <xs:element name="eyes_color" type="eyes_color"/>
            </xs:sequence>
        </xs:choice>
    </xs:group>

    <!--            EYES COLOR-->
    <xs:simpleType name="eyes_color">
        <xs:restriction base="xs:string">
            <xs:enumeration value="green"/>
            <xs:enumeration value="grey"/>
            <xs:enumeration value="blue"/>
            <xs:enumeration value="brown"/>
        </xs:restriction>
    </xs:simpleType>


    <!--            HAIR COLOR-->
    <xs:simpleType name="hair_color">
        <xs:restriction base="xs:string">
            <xs:enumeration value="blond"/>
            <xs:enumeration value="grey"/>
            <xs:enumeration value="black"/>
            <xs:enumeration value="brown"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="future">
        <xs:complexContent>
            <xs:extension base="husband">
                <xs:sequence>
                    <!--            ODDS-->
                    <xs:element name="odds" minOccurs="0" maxOccurs="1">
                        <xs:simpleType>
                            <xs:restriction base="xs:double">
                                <xs:minInclusive value="0.0"/>
                                <xs:maxInclusive value="100.0"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="current">
        <xs:complexContent>
            <xs:extension base="husband">
                <xs:sequence>
                    <xs:element name="wedding_date" type="xs:date"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="past">
        <xs:complexContent>
            <xs:extension base="husband">
                <xs:sequence>
                    <xs:element name="wedding_date">
                    </xs:element>
                    <xs:element name="divorce_date">
                    </xs:element>
                    <xs:element name="reason" type="xs:string" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="register">
        <xs:complexType>
            <xs:choice>
                <xs:element name="husband" maxOccurs="200"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== natahiko/XML-Trainings/JAXB4/valid-husbands.xml
<?xml version="1.0"?>
<register xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="husband.xsd">
    <husband xsi:type="future">
        <name>John Smith</name>
        <email>smith55444_john33@gmail.com</email>
        <hair_color>blond</hair_color>
        <eyes_color>blue</eyes_color>
        <height>185</height>
    </husband>

    <husband xsi:type="future">
        <name>Alex Grey</name>
        <email>grey_alx@gmail.com</email>
        <eyes_color>grey</eyes_color>
        <hair_color>grey</hair_color>
        <height>183.0</height>
        <odds>2.0</odds>
    </husband>

    <husband xsi:type="current">
        <name>Steven Stalone</name>
        <email>stalone33@gmail.com</email>
        <eyes_color>green</eyes_color>
        <hair_color>black</hair_color>
        <height>173.0</height>
        <wedding_date>2005-05-23</wedding_date>
    </husband>

    <husband xsi:type="past">
        <name>Ivan Ivanov</name>
        <email>ivan@gmail.com</email>
        <eyes_color>blue</eyes_color>
        <hair_color>blond</hair_color>
        <height>175.0</height>
        <wedding_date>2000-03-23</wedding_date>
        <divorce_date>2000-04-03</divorce_date>
        <reason>He said that i'm fat</reason>
    </husband>

    <husband xsi:type="past">
        <name>Peter Dubinsliy</name>
        <email>petro33@gmail.com</email>
        <eyes_color>green</eyes_color>
        <hair_color>brown</hair_color>
        <height>156.0</height>
        <wedding_date>2000-03-23</wedding_date>
        <divorce_date>2002-05-23</divorce_date>
    </husband>

</register>
